### PR TITLE
Palette bug fixed,Template renewed with necessary missing modules

### PR DESCRIPTION
**Pull request by abhiskaushik**
Older Web Template
Newly Fixed Web Template

Fixes:
1.Palette Dimension were not changing with Text-Area Dimensions.
2.Graphics library were missing in older template.

### CODE REVIEW

**Comment by samdroid-apps** [comment]
1) This is a bug from the toolkit, there should be a fox in the toolkit

2) doesn't volo add the libs?

**Comment by samdroid-apps** [comment]
Sorry for the typo, there should be no foxes in the toolkit.  There should be a fox in the toolkit.

**Comment by samdroid-apps** [comment]
Sorry about the typo again, there should be a **fix** in the toolkit.

**Comment by godiard** [comment]
Ha ha :)

Also, why modify 53 files?

**Comment by abhiskaushik** [comment]
@godiard  it missed the graphics libs, i added those, so it looked 53 modifications. 
@SAMdroid-apps  yeah <code>volo</code> add but why not have necessary libs, directly inside instead of downloading. Also i need help in fixing toolkit bug.

**Comment by godiard** [comment]
@stndlkr200, I think the files from sugar-web are not included on purpose, to avoid have the same files in two repositories.

**Comment by abhiskaushik** [comment]
how do i configure the toolkit so that activity gets created with the present template inside sugar build instead of fetching it from Downloading: https://codeload.github.com/sugarlabs/sugar-web/legacy.zip/master

**Comment by samdroid-apps** [comment]
@stndlkr200, volo add worked 100% perfect for me yesterday or so.  Are you behind a proxy?

**Comment by samdroid-apps** [comment]
@stndlkr200, we use volo like we use a package manager.  It keeps all the libs up do date, even when you have lots of libs and your own repo.  It also keeps everything cleaner :)

**Comment by godiard** [comment]
Close because need be fixed in sugar-web

**Pull request closed without merging**
